MusicApp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:index] do
    resources :tracks, only: [:new]
  end
  
  resources :tracks

  resources :notes, only: [:create, :destroy]

end

MusicApp/app/models/album.rb
class Album < ApplicationRecord
  validates :name, :band_id, presence: true

  has_many :tracks, dependent: :destroy
  belongs_to :band
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

MusicApp/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks,
    through: :albums,
    source: :tracks
end

MusicApp/app/models/note.rb
class Note < ApplicationRecord
  validates :user_id, :track_id, presence: true

  belongs_to :user

  belongs_to :track
end

MusicApp/app/models/track.rb
class Track < ApplicationRecord
  validates :name, :album_id, presence: true

  belongs_to :album
  has_one :band,
    through: :album,
    source: :band


  has_many :notes, dependent: :destroy
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :notes, dependent: :destroy

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    # session[:session_token] = nil
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end


  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil

  end


  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end


end

MusicApp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :logged_in?


  def show
    @album = Album.find_by(id: params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_url(@album.band_id)
    else
      redirect_to new_band_album_url
    end
  end

  def edit
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Incorrect attributes"]
      redirect_to edit_album_url(@album)
    end
  end

  def destroy
    @album = Album.find(params[:id])
    if @album
      @album.destroy
      redirect_to bands_url
    end
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :name, :style)
  end

end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def logged_in?
    if current_user
      true
    else
      redirect_to new_session_url
    end
  end

  def login!(user)
    @current_user = user
    user.ensure_session_token
    user.save
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end


  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])

  end
end

MusicApp/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :logged_in?

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band
      render :show
    else
      flash.now[:errors] = ["Band 404"]
      redirect_to bands_url
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to bands_url
    else
      flash.now[:errors] = ["Incorrect attributes"]
      redirect_to edit_band_url(@band)
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band
      @band.destroy
      redirect_to bands_url
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

MusicApp/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    note = Note.new(note_params)

    note.save
    redirect_to track_url(note.track_id)
  end

  def destroy
    note = Note.find(params[:id])
    if note.user_id == current_user.id
      note.destroy
      redirect_to track_url(note.track_id)
    end
  end

  private

  def note_params
    params.require(:note).permit(:text, :track_id, :user_id)
  end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create

    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to bands_url
    else
      flash.now[:erorrs] = "Invalid credentials"
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

end

MusicApp/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :logged_in?

  def show
    @track = Track.find_by(id: params[:id])
    render :show
  end

  def new
    @album = Album.find(params[:album_id])
    @track = Track.new
    render :new
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to album_url(@track.album_id)
    else
      redirect_to new_album_track_url
    end
  end

  def edit
    @track = Track.find(params[:id])
    @album = Album.find(@track.album_id)
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    if @track.update_attributes(track_params)
      redirect_to album_url(@track.album_id)
    else
      flash.now[:errors] = ["Incorrect attributes"]
      redirect_to edit_track_url(@track)
    end
  end

  def destroy
    @track = Track.find(params[:id])
    if @track
      @track.destroy
      redirect_to albums_url(@track.album_id)
    end
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :lyrics)
  end

end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      # TODO redirect_to index page
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user
      render :show
    else
      redirect_to new_session_url
    end
  end


  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

MusicApp/app/helpers/albums_helper.rb
module AlbumsHelper
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/helpers/bands_helper.rb
module BandsHelper
end

MusicApp/app/helpers/notes_helper.rb
module NotesHelper
end

MusicApp/app/helpers/sessions_helper.rb
module SessionsHelper
end

MusicApp/app/helpers/tracks_helper.rb
module TracksHelper
end

MusicApp/app/helpers/users_helper.rb
module UsersHelper
end

MusicApp/app/views/albums/_form.html.erb
<% if @album.name %>
  <% action_url = album_url(@album) %>
  <% else %>
  <% action_url = albums_url %>
  <% end %>
<form action="<%= action_url %>" method="post">
  <% if @album.name %>
    <input type="hidden" name="_method" value="Patch">
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="album_name">Album Name</label>
  <input type="text" name="album[name]" value="<%= @album.name %>" id="album_name">
  <label for="style">Style</label>
  <input type="text" name="album[style]" id="style" value="<%=@album.style%>" >

  <input type="hidden" name="album[band_id]" value="<%=@band.id%>">

  <input type="submit" value="<%= @album.name.nil? ? 'Create' : 'Update' %>">
</form>

MusicApp/app/views/albums/edit.html.erb
<h3>Edit album</h3>

<%= render "form" %>

MusicApp/app/views/albums/new.html.erb
<h3>Create new album</h3>
<%= render "form" %>

MusicApp/app/views/albums/show.html.erb
<%= @album.name %>

<%= button_to "Back", band_url(@album.band_id), method: :get %>


<br><br><br><br>
<ul>
  <% @album.tracks.each do |track| %>
    <li>
      <%= link_to track.name, track_url(track), method: :get %>
    </li>
  <% end %>
</ul>

<%= button_to "Add Track", new_album_track_url(@album), method: :get %>
<%= button_to "Edit", edit_album_url(@album), method: :get %>
<%= button_to "Delete", album_url(@album), method: :delete %>

MusicApp/app/views/bands/_form.html.erb
<% if @band.name %>
  <% action_url = band_url(@band) %>
  <% else %>
  <% action_url = bands_url %>
  <% end %>
<form action="<%= action_url %>" method="post">
  <% if @band.name %>
    <input type="hidden" name="_method" value="Patch">
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label>
  <input type="text" name="band[name]" value="<%= @band.name %>" id="band_name">

  <input type="submit" value="<%= @band.name.nil? ? 'Create' : 'Update' %>">
</form>

MusicApp/app/views/bands/edit.html.erb
<h3>Edit band</h3>
<br></br>
<%= render "form" %>

MusicApp/app/views/bands/index.html.erb
<h3>List of all bands</h3>
<ul>
<% @bands.each do |band| %>
<li><%= link_to band.name, band_url(band) %></li>
<% end %>

</ul>

<br><br><br>
<%= button_to "Create New Band...", new_band_url, method: :get %>

MusicApp/app/views/bands/new.html.erb
<h3>Create band</h3>
<br></br>
<%= render "form" %>

MusicApp/app/views/bands/show.html.erb
<h3><%= @band.name %></h3>

<%= button_to "Back", bands_url, method: :get %>

<ul>
  <% @band.albums.each do |album| %>
    <li><%= link_to album.name, album_url(album) %></li>
  <% end %>
</ul>

<%= button_to "Add Album", new_band_album_url(@band), method: :get %>
<%= button_to "Edit Band", edit_band_url(@band), method: :get %>
<%= button_to "Delete Band", band_url(@band) , method: :delete %>

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if current_user  %>

      <%= button_to "logout", session_url, method: :delete   %>
    <% end %>

    <%= yield %>
  </body>
</html>

MusicApp/app/views/tracks/_form.html.erb
<% if @track.name %>
  <% action_url = track_url(@track) %>
  <% else %>
  <% action_url = tracks_url %>
  <% end %>
<form action="<%= action_url %>" method="post">
  <% if @track.name %>
    <input type="hidden" name="_method" value="Patch">
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="track_name">Track Name</label>
  <input type="text" name="track[name]" value="<%= @track.name %>" id="track_name">
  <label for="lyrics">Lyrics</label>

  <textarea id="lyrics" name="track[lyrics]" ><%=@track.lyrics%></textarea>
  <input type="hidden" name="track[album_id]" value="<%=@album.id%>">

  <input type="submit" value="<%= @track.name.nil? ? 'Create' : 'Update' %>">
</form>

MusicApp/app/views/tracks/edit.html.erb
<h3>Edit Track</h3>

<%= render "form" %>

MusicApp/app/views/tracks/new.html.erb
<h3>Add New Track</h3>

<%= render "form" %>

MusicApp/app/views/tracks/show.html.erb
<p>Title:</p>
<%= @track.name %>
<br><br>

<%= button_to "Back", album_url(@track.album_id), method: :get %>

<br><br>

<p>Lyrics:</p>
<%= @track.lyrics %>

<%= button_to "Edit", edit_track_url(@track), method: :get %>
<%= button_to "Delete", track_url(@track), method: :delete %>

<br><br><br>

<ul>
<% @track.notes.each do |note| %>
  <li><%= note.text %> - <%= note.user.email %></li>
  <% if note.user_id == current_user.id %>
    <%= button_to "Delete", note_url(note), method: :delete %>
  <% end %>
<% end %>
</ul>

<form action="<%=notes_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="note[track_id]" value="<%=@track.id%>">
  <input type="hidden" name="note[user_id]" value="<%=current_user.id%>">

  <label for="note"></label>
  <textarea id="note" name="note[text]" placeholder="Write a Comment"></textarea>

  <input type="submit" value="post">

</form>

MusicApp/app/views/users/new.html.erb
<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="email">Email</label>
  <input type="text" name="user[email]" id="email">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">

  <input type="submit">
</form>

MusicApp/app/views/users/show.html.erb
<h1>
<%= @user.email %>
</h1>